"use server";

/**
 * Products Service
 *
 * Server Actions for product CRUD operations.
 * Products support variants (price, stock) and multiple images.
 *
 * Functions:
 * - getProducts() - List all products with relations
 * - getProduct(id) - Get single product by ID
 * - getProductBySlug(slug) - Get product by URL slug
 * - getProductsByCategory(categoryId) - Filter by category
 * - searchProducts(query) - Full-text search
 * - addProduct(formData) - Create product with variants/images
 * - updateProduct(id, formData) - Update product
 * - deleteProduct(id) - Delete product (admin only)
 * - toggleProductStatus(id) - Toggle active/inactive
 *
 * Storage: Images stored in 'product-images' bucket (2MB limit)
 */

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import { hasAdminAccess, isAdmin } from "@/lib/auth/roles";

// ============================================================================
// Types
// ============================================================================

export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  category_id: string;
  category: string; // Alias for backwards compatibility
  category_name?: string;
  is_active: boolean;
  created_at: string;
  // Relations
  images?: ProductImage[];
  primary_image?: ProductImage;
  variants?: ProductVariant[];
  category_data?: {
    id: string;
    name: string;
    slug: string;
    has_variants?: boolean;
  };
}

export interface ProductImage {
  id: string;
  product_id: string;
  url: string;
  image_url?: string;
  is_primary: boolean;
  display_order: number;
}

export interface ProductVariant {
  id: string;
  product_id: string;
  price: number;
  compare_price: number | null;
  stock: number;
  is_active: boolean;
  sku?: string | null;
  size?: string | null; // S, M, L, XL, XXL
  color?: string | null;
}

// Form data types for variants
interface VariantFormInput {
  id?: string;
  price: number;
  compare_price?: number | null;
  stock: number;
  is_active: boolean;
  sku?: string | null;
  size?: string | null;
  color?: string | null;
}

interface ActionResult {
  ok: boolean;
  error?: string;
}

interface AddProductResult extends ActionResult {
  productId?: string;
}

interface GetProductsResult extends ActionResult {
  data?: Product[];
}

interface GetProductResult extends ActionResult {
  data?: Product;
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Extract storage path from Supabase public URL
 * URL format: https://xxx.supabase.co/storage/v1/object/public/bucket-name/path/to/file.ext
 */
function extractStoragePath(publicUrl: string): string | null {
  try {
    const url = new URL(publicUrl);
    const pathParts = url.pathname.split("/storage/v1/object/public/");
    if (pathParts.length === 2) {
      // Remove bucket name from path
      const fullPath = pathParts[1];
      const bucketAndPath = fullPath.split("/");
      // Remove the first element (bucket name) and join the rest
      return bucketAndPath.slice(1).join("/");
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Delete images from storage by extracting paths from public URLs
 */
async function deleteImagesFromStorage(
  supabase: Awaited<ReturnType<typeof createClient>>,
  imageUrls: string[]
): Promise<void> {
  const storagePaths = imageUrls
    .map(extractStoragePath)
    .filter((path): path is string => path !== null);

  if (storagePaths.length > 0) {
    const { error } = await supabase.storage
      .from("product-images")
      .remove(storagePaths);
    if (error) {
      console.error("Failed to delete images from storage:", error);
    }
  }
}

// ============================================================================
// CRUD Operations
// ============================================================================

/**
 * Add a new product with variants
 * - Slug is auto-generated by database trigger
 * - Both admin and demo_admin can create
 * - Images are stored in product_images table
 * - Variants are stored in product_variants table
 */
export async function addProduct(
  formData: FormData
): Promise<AddProductResult> {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // Both admin and demo_admin can create
    if (!hasAdminAccess(user)) {
      return { ok: false, error: "Admin access required to create products" };
    }

    // Extract form data
    const name = formData.get("name") as string;
    const description = formData.get("description") as string;
    const category_id = formData.get("category_id") as string;
    const is_active = formData.get("is_active") === "true";
    const images = formData.getAll("images") as File[];
    const variantsJson = formData.get("variants") as string;

    // Parse variants
    let variants: VariantFormInput[] = [];
    try {
      variants = variantsJson ? JSON.parse(variantsJson) : [];
    } catch {
      return { ok: false, error: "Invalid variants data" };
    }

    // Insert product - slug is auto-generated by database trigger
    const productData = {
      name,
      description: description || null,
      category_id,
      is_active,
    };

    const { data: product, error: insertError } = await supabase
      .from("products")
      .insert([productData])
      .select("id, slug")
      .single();

    if (insertError) {
      console.error("Insert error:", insertError);
      return {
        ok: false,
        error: `Failed to create product: ${insertError.message}`,
      };
    }

    // Insert variants into product_variants table
    const variantRecords = variants.map((v) => ({
      product_id: product.id,
      price: v.price,
      compare_price: v.compare_price || null,
      stock: v.stock,
      is_active: v.is_active,
      sku: v.sku || null,
      size: v.size || null,
      color: v.color || null,
    }));

    const { error: variantError } = await supabase
      .from("product_variants")
      .insert(variantRecords);

    if (variantError) {
      console.error("Variant insert error:", variantError);
      // Cleanup: delete product
      await supabase.from("products").delete().eq("id", product.id);
      return {
        ok: false,
        error: `Failed to create variants: ${variantError.message}`,
      };
    }

    // Upload images and add to product_images table
    const imageUrls: string[] = [];
    for (let i = 0; i < images.length; i++) {
      const image = images[i];
      if (image.size === 0) continue;

      const fileExt = image.name.split(".").pop();
      const fileName = `${name}-${Date.now()}-${i + 1}.${fileExt}`;
      const filePath = `${name}/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from("product-images")
        .upload(filePath, image, {
          cacheControl: "3600",
          upsert: false,
        });

      if (uploadError) {
        console.error("Upload error:", uploadError);
        // Cleanup: delete product and already uploaded images
        await supabase.from("products").delete().eq("id", product.id);
        await deleteImagesFromStorage(supabase, imageUrls);
        return { ok: false, error: `Failed to upload image: ${image.name}` };
      }

      const { data: urlData } = supabase.storage
        .from("product-images")
        .getPublicUrl(filePath);

      imageUrls.push(urlData.publicUrl);

      // Insert into product_images table with public URL
      await supabase.from("product_images").insert([
        {
          product_id: product.id,
          image_url: urlData.publicUrl,
          is_primary: i === 0, // First image is primary
        },
      ]);
    }

    revalidatePath("/admin/products");
    return { ok: true, productId: product.id };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Add product error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Update an existing product with variants
 * - Slug is auto-updated by database trigger when name changes
 * - Handles image additions and deletions
 * - Handles variant updates (delete existing and insert new)
 */
export async function updateProduct(
  id: string,
  formData: FormData
): Promise<ActionResult> {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // Both admin and demo_admin can update
    if (!hasAdminAccess(user)) {
      return { ok: false, error: "Admin access required to update products" };
    }

    // Extract form data
    const name = formData.get("name") as string;
    const description = formData.get("description") as string;
    const category_id = formData.get("category_id") as string;
    const is_active = formData.get("is_active") === "true";
    const newImages = formData.getAll("images") as File[];
    const variantsJson = formData.get("variants") as string;
    const deletedImageIdsJson = formData.get("deleted_image_ids") as string;
    const deletedImageIds: string[] = deletedImageIdsJson
      ? JSON.parse(deletedImageIdsJson)
      : [];

    // Parse variants
    let variants: VariantFormInput[] = [];
    try {
      variants = variantsJson ? JSON.parse(variantsJson) : [];
    } catch {
      return { ok: false, error: "Invalid variants data" };
    }

    if (variants.length === 0) {
      return { ok: false, error: "At least one variant is required" };
    }

    // Get current product slug for image naming
    const { data: currentProduct } = await supabase
      .from("products")
      .select("slug")
      .eq("id", id)
      .single();

    // Delete removed images from storage and database
    if (deletedImageIds.length > 0) {
      const { data: imagesToDelete } = await supabase
        .from("product_images")
        .select("image_url")
        .in("id", deletedImageIds);

      if (imagesToDelete) {
        await deleteImagesFromStorage(
          supabase,
          imagesToDelete.map((img) => img.image_url)
        );
        await supabase
          .from("product_images")
          .delete()
          .in("id", deletedImageIds);
      }
    }

    // Upload new images
    const slug = currentProduct?.slug || id;

    for (let i = 0; i < newImages.length; i++) {
      const image = newImages[i];
      if (image.size === 0) continue;

      const fileExt = image.name.split(".").pop();
      const fileName = `${slug}-${Date.now()}-${i + 1}.${fileExt}`;
      const filePath = `products/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from("product-images")
        .upload(filePath, image, {
          cacheControl: "3600",
          upsert: false,
        });

      if (uploadError) {
        console.error("Upload error:", uploadError);
        return { ok: false, error: `Failed to upload image: ${image.name}` };
      }

      const { data: urlData } = supabase.storage
        .from("product-images")
        .getPublicUrl(filePath);

      // Insert new image with public URL
      await supabase.from("product_images").insert([
        {
          product_id: id,
          image_url: urlData.publicUrl,
          is_primary: false, // Existing images keep primary status
        },
      ]);
    }

    // Check if product has at least one image after changes
    const { count: imageCount } = await supabase
      .from("product_images")
      .select("id", { count: "exact", head: true })
      .eq("product_id", id);

    if ((imageCount || 0) === 0) {
      return { ok: false, error: "At least one image is required" };
    }

    // Update variants: delete existing and insert new
    // First, delete all existing variants for this product
    await supabase.from("product_variants").delete().eq("product_id", id);

    // Insert new variants
    const variantRecords = variants.map((v) => ({
      product_id: id,
      price: v.price,
      compare_price: v.compare_price || null,
      stock: v.stock,
      is_active: v.is_active,
      sku: v.sku || null,
      size: v.size || null,
      color: v.color || null,
    }));

    const { error: variantError } = await supabase
      .from("product_variants")
      .insert(variantRecords);

    if (variantError) {
      console.error("Variant update error:", variantError);
      return {
        ok: false,
        error: `Failed to update variants: ${variantError.message}`,
      };
    }

    // Update product - slug is auto-updated by database trigger
    const productData = {
      name,
      description: description || null,
      category_id,
      is_active,
    };

    const { error: updateError } = await supabase
      .from("products")
      .update(productData)
      .eq("id", id);

    if (updateError) {
      console.error("Update error:", updateError);
      return { ok: false, error: "Failed to update product" };
    }

    revalidatePath("/admin/products");
    return { ok: true };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Update product error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Delete a product (admin only)
 * Also deletes all images from storage
 */
export async function deleteProduct(id: string): Promise<ActionResult> {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // Only full admin can delete
    if (!isAdmin(user)) {
      return { ok: false, error: "Only admin users can delete products" };
    }

    // Get all product images to delete from storage
    const { data: images } = await supabase
      .from("product_images")
      .select("image_url")
      .eq("product_id", id);

    // Delete images from storage
    if (images && images.length > 0) {
      await deleteImagesFromStorage(
        supabase,
        images.map((img) => img.image_url)
      );
    }

    // Delete product (cascades to product_images, product_variants)
    const { error: deleteError } = await supabase
      .from("products")
      .delete()
      .eq("id", id);

    if (deleteError) {
      console.error("Delete error:", deleteError);
      return { ok: false, error: "Failed to delete product" };
    }

    revalidatePath("/admin/products");
    return { ok: true };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Delete product error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Toggle product status by updating all variants' is_active status
 * - If any variant is active, set all to inactive
 * - If all variants are inactive, set all to active
 * - Both admin and demo_admin can toggle
 */
export async function toggleProductStatus(id: string): Promise<ActionResult> {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // Both admin and demo_admin can toggle status
    if (!hasAdminAccess(user)) {
      return {
        ok: false,
        error: "Admin access required to toggle product status",
      };
    }

    // Get current variants to determine new status
    const { data: variants, error: fetchError } = await supabase
      .from("product_variants")
      .select("id, is_active")
      .eq("product_id", id);

    if (fetchError) {
      console.error("Fetch variants error:", fetchError);
      return { ok: false, error: "Failed to fetch product variants" };
    }

    if (!variants || variants.length === 0) {
      return { ok: false, error: "Product has no variants to toggle" };
    }

    // Determine new status: if any variant is active, deactivate all; otherwise activate all
    const hasActiveVariant = variants.some((v) => v.is_active);
    const newStatus = !hasActiveVariant;

    // Update all variants
    const { error: updateError } = await supabase
      .from("product_variants")
      .update({ is_active: newStatus })
      .eq("product_id", id);

    if (updateError) {
      console.error("Update error:", updateError);
      return { ok: false, error: "Failed to toggle product status" };
    }

    revalidatePath("/admin/products");
    return { ok: true };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Toggle product status error:", e);
    return { ok: false, error: message };
  }
}

// ============================================================================
// Read Operations
// ============================================================================

/**
 * Get all products with category info, images, and variants
 */
export async function getProducts(): Promise<GetProductsResult> {
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category_id(id, name, slug),
        images:product_images(id, image_url, is_primary),
        variants:product_variants(id, price, compare_price, stock, is_active, sku, size, color)
      `
      )
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Fetch error:", error);
      return { ok: false, error: "Failed to fetch products", data: [] };
    }

    // Transform data
    const products = (data || []).map((product) => {
      const images = (product.images || []).map(
        (img: { id: string; image_url: string; is_primary: boolean }) => ({
          ...img,
          url: img.image_url, // Map image_url to url for backwards compatibility
        })
      );
      const primaryImage =
        images.find((img: ProductImage) => img.is_primary) || images[0];

      // Derive is_active from variants - product is active if any variant is active
      const variants = product.variants || [];
      const is_active = variants.some(
        (v: { is_active: boolean }) => v.is_active
      );

      return {
        ...product,
        is_active,
        category: product.category_id, // Alias for backwards compatibility
        category_name: product.category_data?.name || product.category_id,
        primary_image: primaryImage,
        images,
      };
    });

    return { ok: true, data: products };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Get products error:", e);
    return { ok: false, error: message, data: [] };
  }
}

/**
 * Get a single product by ID with full details
 */
export async function getProduct(id: string): Promise<GetProductResult> {
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category_id(id, name, slug),
        images:product_images(id, image_url, is_primary),
        variants:product_variants(id, price, compare_price, stock, is_active, sku, size, color)
      `
      )
      .eq("id", id)
      .single();

    if (error) {
      console.error("Fetch error:", error);
      return { ok: false, error: "Product not found" };
    }

    // Transform data
    const images = (data.images || []).map(
      (img: { id: string; image_url: string; is_primary: boolean }) => ({
        ...img,
        url: img.image_url, // Map image_url to url for backwards compatibility
      })
    );
    const primaryImage =
      images.find((img: ProductImage) => img.is_primary) || images[0];

    // Derive is_active from variants - product is active if any variant is active
    const variants = data.variants || [];
    const is_active = variants.some((v: { is_active: boolean }) => v.is_active);

    const product = {
      ...data,
      is_active,
      category: data.category_id, // Alias for backwards compatibility
      category_name: data.category_data?.name || data.category_id,
      primary_image: primaryImage,
      images,
    };

    return { ok: true, data: product };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Get product error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Get products by category
 */
export async function getProductsByCategory(
  categoryId: string
): Promise<GetProductsResult> {
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category_id(id, name, slug),
        images:product_images(id, image_url, is_primary),
        variants:product_variants(id, price, compare_price, stock, is_active, sku, size, color)
      `
      )
      .eq("category_id", categoryId)
      .eq("is_active", true)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Fetch error:", error);
      return { ok: false, error: "Failed to fetch products", data: [] };
    }

    const products = (data || []).map((product) => {
      const images = (product.images || []).map(
        (img: { id: string; image_url: string; is_primary: boolean }) => ({
          ...img,
          url: img.image_url, // Map image_url to url for backwards compatibility
        })
      );
      const primaryImage =
        images.find((img: ProductImage) => img.is_primary) || images[0];

      return {
        ...product,
        category: product.category_id, // Alias for backwards compatibility
        category_name: product.category_data?.name || product.category_id,
        primary_image: primaryImage,
        images,
      };
    });

    return { ok: true, data: products };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Get products by category error:", e);
    return { ok: false, error: message, data: [] };
  }
}

/**
 * Check if a category requires variants (has configured attributes)
 */
export async function categoryRequiresVariants(
  categoryId: string
): Promise<boolean> {
  try {
    const supabase = await createClient();

    const { count } = await supabase
      .from("category_attributes")
      .select("id", { count: "exact", head: true })
      .eq("category_id", categoryId);

    return (count || 0) > 0;
  } catch (e) {
    console.error("Check category variants error:", e);
    return false;
  }
}

/**
 * Get a single product by slug with full details
 */
export async function getProductBySlug(
  slug: string
): Promise<GetProductResult> {
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category_id(id, name, slug),
        images:product_images(id, image_url, is_primary),
        variants:product_variants(id, price, compare_price, stock, is_active, sku, size, color)
      `
      )
      .eq("slug", slug)
      .single();

    if (error) {
      console.error("Fetch error:", error);
      return { ok: false, error: "Product not found" };
    }

    // Transform data
    const images = (data.images || []).map(
      (img: { id: string; image_url: string; is_primary: boolean }) => ({
        ...img,
        url: img.image_url,
      })
    );
    const primaryImage =
      images.find((img: ProductImage) => img.is_primary) || images[0];

    const product = {
      ...data,
      category: data.category_id,
      category_name: data.category_data?.name || data.category_id,
      primary_image: primaryImage,
      images,
    };

    return { ok: true, data: product };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Get product by slug error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Search products by name (for autocomplete/search functionality)
 * Returns active products matching the search query
 */
export async function searchProducts(
  query: string,
  limit: number = 10
): Promise<GetProductsResult> {
  try {
    if (!query || query.trim().length < 2) {
      return { ok: true, data: [] };
    }

    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category_id(id, name, slug),
        images:product_images(id, image_url, is_primary),
        variants:product_variants(id, price, compare_price, stock, is_active, sku, size, color)
      `
      )
      .eq("is_active", true)
      .ilike("name", `%${query}%`)
      .order("name", { ascending: true })
      .limit(limit);

    if (error) {
      console.error("Search error:", error);
      return { ok: false, error: "Failed to search products", data: [] };
    }

    // Transform data
    const products = (data || []).map((product) => {
      const images = (product.images || []).map(
        (img: { id: string; image_url: string; is_primary: boolean }) => ({
          ...img,
          url: img.image_url,
        })
      );
      const primaryImage =
        images.find((img: ProductImage) => img.is_primary) || images[0];

      return {
        ...product,
        category: product.category_id,
        category_name: product.category_data?.name || product.category_id,
        primary_image: primaryImage,
        images,
      };
    });

    return { ok: true, data: products };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Search products error:", e);
    return { ok: false, error: message, data: [] };
  }
}
