"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import { hasAdminAccess, isAdmin } from "@/lib/auth/roles";

// ============================================================================
// Types
// ============================================================================

export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  compare_price: number | null;
  category: string;
  category_name?: string;
  stock: number;
  sku: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  // Relations
  images?: ProductImage[];
  primary_image?: ProductImage;
  variants?: ProductVariant[];
  category_data?: {
    id: string;
    name: string;
    slug: string;
    has_variants?: boolean;
  };
}

export interface ProductImage {
  id: string;
  product_id: string;
  variant_id: string | null;
  url: string;
  alt_text: string | null;
  is_primary: boolean;
  display_order: number;
}

export interface ProductVariant {
  id: string;
  product_id: string;
  sku: string | null;
  price_adjustment: number;
  stock: number;
  is_active: boolean;
  attributes?: VariantAttribute[];
}

export interface VariantAttribute {
  attribute_type: string;
  attribute_value: string;
  hex_code?: string | null;
}

interface ActionResult {
  ok: boolean;
  error?: string;
}

interface AddProductResult extends ActionResult {
  productId?: string;
}

interface GetProductsResult extends ActionResult {
  data?: Product[];
}

interface GetProductResult extends ActionResult {
  data?: Product;
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Extract storage path from a Supabase public URL
 */
function extractStoragePath(url: string, bucket: string): string | null {
  const match = url.match(new RegExp(`/${bucket}/(.+)$`));
  return match ? match[1] : null;
}

/**
 * Delete images from storage
 */
async function deleteImagesFromStorage(
  supabase: Awaited<ReturnType<typeof createClient>>,
  imageUrls: string[]
): Promise<void> {
  const paths = imageUrls
    .map((url) => extractStoragePath(url, "product-images"))
    .filter((path): path is string => path !== null);

  if (paths.length > 0) {
    const { error } = await supabase.storage
      .from("product-images")
      .remove(paths);
    if (error) {
      console.error("Failed to delete images from storage:", error);
    }
  }
}

// ============================================================================
// CRUD Operations
// ============================================================================

/**
 * Add a new product
 * - Slug is auto-generated by database trigger
 * - Both admin and demo_admin can create
 * - Images are stored in product_images table
 */
export async function addProduct(
  formData: FormData
): Promise<AddProductResult> {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // Both admin and demo_admin can create
    if (!hasAdminAccess(user)) {
      return { ok: false, error: "Admin access required to create products" };
    }

    // Extract form data
    const name = formData.get("name") as string;
    const description = formData.get("description") as string;
    const price = parseFloat(formData.get("price") as string);
    const comparePriceStr = formData.get("compare_price") as string;
    const compare_price = comparePriceStr ? parseFloat(comparePriceStr) : null;
    const category = formData.get("category") as string;
    const stock = parseInt(formData.get("stock") as string) || 0;
    const sku = formData.get("sku") as string;
    const is_active = formData.get("is_active") === "true";
    const images = formData.getAll("images") as File[];

    // Validate required fields
    if (!name || !category) {
      return { ok: false, error: "Name and category are required bbb" };
    }

    if (!price || price < 1) {
      return { ok: false, error: "Price must be at least 1" };
    }

    if (images.length === 0 || images.every((img) => img.size === 0)) {
      return { ok: false, error: "At least one image is required" };
    }

    // Insert product - slug is auto-generated by database trigger
    const productData = {
      name,
      description: description || null,
      price,
      compare_price,
      category,
      stock,
      sku: sku || null,
      is_active,
    };

    const { data: product, error: insertError } = await supabase
      .from("products")
      .insert([productData])
      .select("id, slug")
      .single();

    if (insertError) {
      console.error("Insert error:", insertError);
      return {
        ok: false,
        error: `Failed to create product: ${insertError.message}`,
      };
    }

    // Upload images and add to product_images table
    const imageUrls: string[] = [];
    for (let i = 0; i < images.length; i++) {
      const image = images[i];
      if (image.size === 0) continue;

      const fileExt = image.name.split(".").pop();
      const fileName = `${product.slug}-${Date.now()}-${i + 1}.${fileExt}`;
      const filePath = `products/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from("product-images")
        .upload(filePath, image, {
          cacheControl: "3600",
          upsert: false,
        });

      if (uploadError) {
        console.error("Upload error:", uploadError);
        // Cleanup: delete product and already uploaded images
        await supabase.from("products").delete().eq("id", product.id);
        await deleteImagesFromStorage(supabase, imageUrls);
        return { ok: false, error: `Failed to upload image: ${image.name}` };
      }

      const { data: urlData } = supabase.storage
        .from("product-images")
        .getPublicUrl(filePath);

      imageUrls.push(urlData.publicUrl);

      // Insert into product_images table
      await supabase.from("product_images").insert([
        {
          product_id: product.id,
          url: urlData.publicUrl,
          is_primary: i === 0, // First image is primary
          display_order: i,
        },
      ]);
    }

    revalidatePath("/admin/products");
    return { ok: true, productId: product.id };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Add product error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Update an existing product
 * - Slug is auto-updated by database trigger when name changes
 * - Handles image additions and deletions
 */
export async function updateProduct(
  id: string,
  formData: FormData
): Promise<ActionResult> {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // Both admin and demo_admin can update
    if (!hasAdminAccess(user)) {
      return { ok: false, error: "Admin access required to update products" };
    }

    // Extract form data
    const name = formData.get("name") as string;
    const description = formData.get("description") as string;
    const price = parseFloat(formData.get("price") as string);
    const comparePriceStr = formData.get("compare_price") as string;
    const compare_price = comparePriceStr ? parseFloat(comparePriceStr) : null;
    const category = formData.get("category") as string;
    const stock = parseInt(formData.get("stock") as string) || 0;
    const sku = formData.get("sku") as string;
    const is_active = formData.get("is_active") === "true";
    const newImages = formData.getAll("images") as File[];
    const existingImageIdsJson = formData.get("existing_image_ids") as string;
    const existingImageIds: string[] = existingImageIdsJson
      ? JSON.parse(existingImageIdsJson)
      : [];
    const deletedImageIdsJson = formData.get("deleted_image_ids") as string;
    const deletedImageIds: string[] = deletedImageIdsJson
      ? JSON.parse(deletedImageIdsJson)
      : [];

    // Validate required fields
    if (!name || !category) {
      return { ok: false, error: "Name and category are required" };
    }

    if (!price || price < 1) {
      return { ok: false, error: "Price must be at least 1" };
    }

    // Get current product slug for image naming
    const { data: currentProduct } = await supabase
      .from("products")
      .select("slug")
      .eq("id", id)
      .single();

    // Delete removed images from storage and database
    if (deletedImageIds.length > 0) {
      const { data: imagesToDelete } = await supabase
        .from("product_images")
        .select("url")
        .in("id", deletedImageIds);

      if (imagesToDelete) {
        await deleteImagesFromStorage(
          supabase,
          imagesToDelete.map((img) => img.url)
        );
        await supabase
          .from("product_images")
          .delete()
          .in("id", deletedImageIds);
      }
    }

    // Upload new images
    const slug = currentProduct?.slug || id;
    const newImageRecords: Array<{ url: string; display_order: number }> = [];

    for (let i = 0; i < newImages.length; i++) {
      const image = newImages[i];
      if (image.size === 0) continue;

      const fileExt = image.name.split(".").pop();
      const fileName = `${slug}-${Date.now()}-${i + 1}.${fileExt}`;
      const filePath = `products/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from("product-images")
        .upload(filePath, image, {
          cacheControl: "3600",
          upsert: false,
        });

      if (uploadError) {
        console.error("Upload error:", uploadError);
        return { ok: false, error: `Failed to upload image: ${image.name}` };
      }

      const { data: urlData } = supabase.storage
        .from("product-images")
        .getPublicUrl(filePath);

      newImageRecords.push({
        url: urlData.publicUrl,
        display_order: existingImageIds.length + i,
      });
    }

    // Insert new images
    if (newImageRecords.length > 0) {
      const insertData = newImageRecords.map((img, idx) => ({
        product_id: id,
        url: img.url,
        is_primary: existingImageIds.length === 0 && idx === 0,
        display_order: img.display_order,
      }));

      await supabase.from("product_images").insert(insertData);
    }

    // Check if product has at least one image after changes
    const { count: imageCount } = await supabase
      .from("product_images")
      .select("id", { count: "exact", head: true })
      .eq("product_id", id);

    if ((imageCount || 0) === 0) {
      return { ok: false, error: "At least one image is required" };
    }

    // Update product - slug is auto-updated by database trigger
    const productData = {
      name,
      description: description || null,
      price,
      compare_price,
      category,
      stock,
      sku: sku || null,
      is_active,
    };

    const { error: updateError } = await supabase
      .from("products")
      .update(productData)
      .eq("id", id);

    if (updateError) {
      console.error("Update error:", updateError);
      return { ok: false, error: "Failed to update product" };
    }

    revalidatePath("/admin/products");
    return { ok: true };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Update product error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Delete a product (admin only)
 * Also deletes all images from storage
 */
export async function deleteProduct(id: string): Promise<ActionResult> {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // Only full admin can delete
    if (!isAdmin(user)) {
      return { ok: false, error: "Only admin users can delete products" };
    }

    // Get all product images to delete from storage
    const { data: images } = await supabase
      .from("product_images")
      .select("url")
      .eq("product_id", id);

    // Delete images from storage
    if (images && images.length > 0) {
      await deleteImagesFromStorage(
        supabase,
        images.map((img) => img.url)
      );
    }

    // Delete product (cascades to product_images, product_variants)
    const { error: deleteError } = await supabase
      .from("products")
      .delete()
      .eq("id", id);

    if (deleteError) {
      console.error("Delete error:", deleteError);
      return { ok: false, error: "Failed to delete product" };
    }

    revalidatePath("/admin/products");
    return { ok: true };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Delete product error:", e);
    return { ok: false, error: message };
  }
}

// ============================================================================
// Read Operations
// ============================================================================

/**
 * Get all products with category info and images
 */
export async function getProducts(): Promise<GetProductsResult> {
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category(id, name, slug),
        images:product_images(id, url, is_primary, display_order)
      `
      )
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Fetch error:", error);
      return { ok: false, error: "Failed to fetch products", data: [] };
    }

    // Transform data
    const products = (data || []).map((product) => {
      const images = product.images || [];
      const primaryImage =
        images.find((img: ProductImage) => img.is_primary) || images[0];

      return {
        ...product,
        category_name: product.category_data?.name || product.category,
        primary_image: primaryImage,
        images: images.sort(
          (a: ProductImage, b: ProductImage) =>
            a.display_order - b.display_order
        ),
      };
    });

    return { ok: true, data: products };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Get products error:", e);
    return { ok: false, error: message, data: [] };
  }
}

/**
 * Get a single product by ID with full details
 */
export async function getProduct(id: string): Promise<GetProductResult> {
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category(id, name, slug),
        images:product_images(id, url, alt_text, is_primary, display_order, variant_id),
        variants:product_variants(
          id, sku, price_adjustment, stock, is_active,
          attributes:variant_attribute_values(
            id,
            attribute_value:attribute_values(
              id, value, hex_code,
              attribute_type:attribute_types(id, name, slug)
            )
          )
        )
      `
      )
      .eq("id", id)
      .single();

    if (error) {
      console.error("Fetch error:", error);
      return { ok: false, error: "Product not found" };
    }

    // Transform data
    const images = data.images || [];
    const primaryImage =
      images.find((img: ProductImage) => img.is_primary) || images[0];

    const product = {
      ...data,
      category_name: data.category_data?.name || data.category,
      primary_image: primaryImage,
      images: images.sort(
        (a: ProductImage, b: ProductImage) => a.display_order - b.display_order
      ),
    };

    return { ok: true, data: product };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Get product error:", e);
    return { ok: false, error: message };
  }
}

/**
 * Get products by category
 */
export async function getProductsByCategory(
  categoryId: string
): Promise<GetProductsResult> {
  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("products")
      .select(
        `
        *,
        category_data:categories!category(id, name, slug),
        images:product_images(id, url, is_primary, display_order)
      `
      )
      .eq("category", categoryId)
      .eq("is_active", true)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Fetch error:", error);
      return { ok: false, error: "Failed to fetch products", data: [] };
    }

    const products = (data || []).map((product) => {
      const images = product.images || [];
      const primaryImage =
        images.find((img: ProductImage) => img.is_primary) || images[0];

      return {
        ...product,
        category_name: product.category_data?.name || product.category,
        primary_image: primaryImage,
        images: images.sort(
          (a: ProductImage, b: ProductImage) =>
            a.display_order - b.display_order
        ),
      };
    });

    return { ok: true, data: products };
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    console.error("Get products by category error:", e);
    return { ok: false, error: message, data: [] };
  }
}

/**
 * Check if a category requires variants (has configured attributes)
 */
export async function categoryRequiresVariants(
  categoryId: string
): Promise<boolean> {
  try {
    const supabase = await createClient();

    const { count } = await supabase
      .from("category_attributes")
      .select("id", { count: "exact", head: true })
      .eq("category_id", categoryId);

    return (count || 0) > 0;
  } catch (e) {
    console.error("Check category variants error:", e);
    return false;
  }
}
